name: Minecraft 24/7 Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Run Minecraft Bot
      env:
        MC_HOST: kiingdomsmp.aternos.me
        MC_PORT: 36463
        MC_USERNAME: GUARDIAN
      run: node bot.js
